version: '3'
services:
  movies:
    image: vishnuvardhanyadhav/moviesimgpaytm:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: vishnuvardhanyadhav/trainimgpaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: vishnuvardhanyadhav/dthimgpaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: vishnuvardhanyadhav/rechargeimgpaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
